name: beacon_monitoring
description: A Flutter plugin for monitoring beacons on mobile platforms. Supports iOS and Android.
version: 1.0.0
homepage: https://github.com/ObjectivityLtd/beacon_monitoring

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  beacon_monitoring_platform_interface: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: uk.co.objectivity.beacon_monitoring
        pluginClass: BeaconMonitoringPlugin
      ios:
        pluginClass: BeaconMonitoringPlugin
